version: '3'
services:
  electrum:
    image: electrum-nmc
    container_name: nmc
    ports:
      - 127.0.0.1:8334:8334
    environment: # these default values do not need to be set
      - ENMC_USER=namecoin
      - ENMC_PASSWORD=namecoinz
      - ENMC_HOST=0.0.0.0
      - ENMC_PORT=8334
    volumes:
      - ./config/electrum-nmc:/data/electrum-nmc
